version: "3"
services:
  api:
    container_name: app
    build:
      context: .
    volumes:
      - .:/src/app
      - /src/app/node_modules
      - ./hackers.db:/src/app/hackers.db
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    ports:
      - 3000:3000
    command: ["npm", "run", "dev"]
